bookmark/urls.py
from django.contrib import admin
from django.urls import path, re_path #re_path는

#가져오기 * 는 전부다 가져온다는 말
from .views import *

#url 이름을 가지고 패턴을 찾고자할 때 namespace를 사용하려면 app_name이 필수!
app_name = 'bookmark'

urlpatterns = [
    #path('list/', 뷰, 이름(이 이름으로 list패턴을 찾고 싶을때-id같이 쓸수있다. css에서 찾아서 쓸때처럼)),
    # path('', list, name='list'), #메인페이지로 쓸떄는 'list'에서 list를 지우면 홈으로 list페이지가 설정됨


    # 함수형뷰 : 함수 이름만
    # 클래스형 뷰 : 클래스이름.as_view()
    path('', BookmarkListView.as_view(), name='list'), #메인페이지로 쓸떄는 'list'에서 list를 지우면 홈으로 list페이지가 설정됨
    path('write/', BookmarkCreateView.as_view(), name='write'),
    #<1:2> - 1: data type, 2: data name 1번은 빠져도 되는데 2번은 빠지면 안된다
    path('detail/<int:pk>', BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BookmarkDeleteView.as_view(), name='delete'),
    # re_path(regexp,,),
    # url(regexp,?,?)
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include #<----2차 토스할떄 이거 추가해야함


#1차 url
urlpatterns = [
    path('admin/', admin.site.urls),
    #1차에서 2차인 bookmark urls로 토스
    path('', include('bookmark.urls')), #bookmark폴더에 urls파일로 토스해주겠다.
]

bookmark/models.py
from django.db import models

# Create your models here.
# 데이터베이스 직접 접근하는 것이 아니라 ORM 기능을 통해서 접근 , 데이터 베이스 몰라도 코드만 잘짜, 코드에만 집중할 수 있게 해준다.
# 모델은 class로 만든다. 꼭, models.Model을 상속 받아야 한다.
# 뭘저장할건지, 어떻게 저장할 건지, 필드만 작성하면 된다

class Bookmark(models.Model):
    # 필드 : 데이터베이스에 어떤 컬럼, 어떤 형태, 어떤 제약조건
    # 필드목적2 : 프론트에서 어떤 from tag와 어떤 제약조건을 설정
    site_name = models.CharField(max_length=100)
    url = models.URLField('Site URL')

# 이다음에는 마이그레이션을 해줘야한다. 그래야 모델이 데이버베이스에 생성된다

    # print 함수를 사용해서 객체를 출력할때 출력될 내용을 반환하는 함수
    # 장고가 이걸 응용해서 화면에 객체를 html로 출력할떄 내용을 반환하는 함수

    #admin 페이지에서 내용 편집할때
    def __str__(self):
        return self.site_name+ " : "+self.url

    class Meta:
        # 해당 모델에 대한 옵션 값
        # 정령, 출력될 모델 이름
        ordering = ['site_name'] #- 붙이면 반대로 정렬

    # Todo : get_absolute_url

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('bookmark:detail', args=[str(self.id)])

#이거하고 뷰로 다시 넘어간다 08

bookmark/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse

# 뷰 종류는 두가지 : 함수형, 클래스형
# 아래건 함수형 뷰임
# 장고 목적? : 귀찮은거 하기 싫어서...
# 클래스형 : 자주 쓰는 기능을 상속받아서 간단하게 생성

# 장고에서 뷰 컴포넌트 불러온다
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# 모델에서 넘어옴 08
# 아래 주석들 다시만듬
# list View
from .models import Bookmark
class BookmarkListView(ListView):
    model = Bookmark
    paginate_by = 3
    # 클래스형 뷰는 기본적으로 렌더링할 템플릿 파일이 지정이 되어 있음
    # bookmark/bookmark_list.html


# urls로 넘어가 서 뷰이름 변경



# 이건 일단 안씀
# def list(request):
#     return HttpResponse("List Page")

from django.urls import reverse_lazy
class BookmarkCreateView(CreateView):
    model = Bookmark #입력화면에 출력된 form tag를 자동으로 만들어줌
    # _form : create, update
    #default : _form 아래 서픽스를 안쓰면 디폴트는 폼
    template_name_suffix = '_create'
    # 입력받을 필드 목록
    fields = ['site_name','url']
    # get_absolute_url
    success_url = reverse_lazy('bookmark:list')



class BookmarkUpdateView(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url']
    template_name_suffix = '_update'
    #동작이 완료된 후 어디로 가냐, 아래거 안쓰면 get absolute url
    # success_url = reverse_lazy('list')


class BookmarkDeleteView(DeleteView):
    model = Bookmark
    #북마크의 리스트 불러와서 메인페이지로
    success_url = reverse_lazy('bookmark:list')


class BookmarkDetailView(DetailView):
    model = Bookmark




# def write(request):
#     return HttpResponse("Write Page")
#
# def update(request):
#     return HttpResponse("Update Page")
#
# def delete(request):
#     return HttpResponse("Delete Page")

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Confirm Delete{% endblock %}
{% block content %}

<form action="" method="post">
    서버로 정보를 전달할떄에는 항상 아래 추가
    {% csrf_token %}
    <div class="alert alert-danger">Do you want to delete Bookmark "{{object}}"?</div>
    <input type="submit" value="Delete" class="btn btn-danger">
</form>


{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}
{% block title %}Bookmark Write{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <!--
            보안에 관련된것 무조건 넣어야 함
        -->

        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Write">

    </form>


{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% block title %}Detail{% endblock %}

{% block content %}
{{object.site_name}}

<br/>
<a href="{{object.url}}" target="_blank">
{{object.url}}</a>

{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% block title %}Bookmarks{% endblock %}
{% block content %}
<div class="btn-group d-block text-right mb-1" role="group">
  <a href="{% url 'bookmark:write' %}" class="btn btn-info">Add</a>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Site</th>
      <th scope="col">URL</th>
      <th scope="col">Modify</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for bookmark in object_list %}
        <tr>
            <td>
                {{ forloop.counter }}
            </td>
            <td>
                <a href="{% url 'bookmark:detail' bookmark.id %}">{{bookmark.site_name}}</a>
            </td>
            <td>
                <a href="{{bookmark.url}}" target="_blank">{{bookmark.url}}</a>
            </td>
            <td>
                <a href="{% url 'bookmark:update' bookmark.id %}" class="btn btn-success btn-sm">modify</a>
            </td>
            <td>
                <a href="{% url 'bookmark:delete' bookmark.id %}" class="btn btn-danger btn-sm">delete</a>
            </td>
        </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}


{% block pagination %}
    {% if is_paginated %}
        <ul class="pagination justify-content-center pagination-sm">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'bookmark:list' %}?page={{page_obj.previous_page_number}}">previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">previous</a>
                </li>

            {% endif %}

            {% for object in page_obj.paginator.page_range %}
                <li class="page-item {% if page_obj.number == forloop.counter %}disabled{% endif %}">
                    <a class="page-link" href="{% url 'bookmark:list' %}?page={{forloop.counter}}">{{forloop.counter}}</a>
                </li>

            {% endfor %}


            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'bookmark:list' %}?page={{page_obj.next_page_number}}">Next</a>
                </li>

            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>

            {% endif %}

        </ul>
    {% endif %}
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}
{% block title %}Bookmark Update{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <!--
            보안에 관련된것 무조건 넣어야 함
        -->

        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Update">

    </form>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>

<div class="container">
    <header class="py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">

          </div>
          <div class="col-4 text-center">
            <a class="header-logo text-dark" href="/">Bookmark</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
          </div>
        </div>
      </header>

    {% block content %}
    {% endblock %}

    {% block pagination %}
    {% endblock %}
</div>

</body>
</html>

<!-- //
공통된 영역
글로벌 네비게이션
사이드 메뉴
카트
로그인
하위 템플릿에서 사용할 블록
// -->